# Generated by Django 6.1.1 on 2026-09-22 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'food'), ('Rent', 'Rent'), ('Travel', 'Travel'), ('Groceries', 'Groceries'), ('Fuel', 'Fuel'), ('shopping', 'shopping'), ('billing', 'billing'), ('medical', 'medical'), ('education', 'education'), ('entertainment', 'entertainment'), ('investment', 'investment'), ('Other', 'Other')], max_length=100)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
